apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: service-one
  namespace: dev
spec:
  template:
    spec:
      containers:
        - image: docker.io/gines/service-one
